---
title: "HR Analysis - Factors important to retain performing employees"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

#### Problem
Factors important to retain performing employees

#### Data
https://www.kaggle.com/ludobenistant/hr-analytics

https://www.kaggle.com/ludobenistant/hr-analytics/downloads/human-resources-analytics.zip


```{r load}
source("hr_efficiency.R")
hr = hrDF()

```
####Data Challenges

#### _Total Employees : `r NROW(hr)`_

#### _Total Employees Left : `r NROW(hr %>% filter(left==1))`_

## Correlation plot - 

####_Observation - Low overall statisfaction, high workload (projects, monthly hours, work accident) & less incentive (promotion)_

```{r correlation, echo=FALSE}

inputPanel(
  sliderInput("n_last_evaluation", label = "Last Evaluation Ratings:",
              min = 0.1, max = 1, value = 0.7, step = 0.1),
  
  sliderInput("n_time_spend_company", label = "time spend company:",
              min = 0, max = 8, value = 4, step = 1),
  sliderInput("n_number_project", label = "number of projects:",
              min = 0, max = 8, value = 5, step = 1)
)

renderPlot({
 plot_correlation(hr,input$n_last_evaluation, input$n_time_spend_company,input$n_number_project)
})
```

## Plot atrition by departments

```{r atrition_dept, echo=FALSE}
plot_atrition_dept(hr)
```

```{r atrition_dept_vw, echo=FALSE}
library(dplyr)
dataByDept <- hr %>% 
  mutate(has_left=if_else(left_f==1, 1, 0) ) %>% 
  mutate(remain=if_else(left_f==0, 1, 0) )  %>% 
  group_by(dept) %>% 
  summarise(quit=sum(has_left), 
            stayed=sum(remain), 
            attrition=round(quit/(quit+stayed),2)) %>% 
  arrange(attrition)
dataByDept
```





